# Generated by Django 4.2.4 on 2023-08-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('estao_civil', models.CharField(choices=[('solteiro', 'solteiro'), ('casado', 'casado'), ('divorciado', 'divorciado')], default='casado', max_length=10)),
            ],
        ),
    ]
