# Generated by Django 4.2.4 on 2023-08-25 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='email',
            field=models.EmailField(max_length=300, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='endereco',
            field=models.CharField(max_length=100, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='matricula',
            field=models.IntegerField(null=True, verbose_name='Matricula'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                     '+99 99 9999-0000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='estao_civil',
            field=models.CharField(choices=[('', ''), ('Solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado')], default='', max_length=10, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='sobrenome',
            field=models.CharField(max_length=50, null=True, verbose_name='Sobrenome'),
        ),
    ]
