# Generated by Django 4.2.4 on 2023-08-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadro', '0002_alter_funcionarios_options_funcionarios_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='cargo',
            field=models.CharField(max_length=60, null=True, verbose_name='Cargo'),
        ),
    ]
